Repository Chiman2937/team1-w1k1ed-project, pull requests merged in 2025-08, with the labels that each got.

#133 fix: 좋아요 클릭했을 때 좋아요가 눌리는 버그 해결
  src/components/page/boardDetail/BoardDetail.tsx
  src/components/page/boardDetail/BoardDetailButton.tsx
  src/components/page/boardDetail/BoardTextArea.tsx
Labels: [🐞 BugFix ], 👽 창환

#139 Bugfix: 토스트 중복 수정
  src/components/common/WikiCreateForm.tsx
Labels: [🐞 BugFix ], 🤓민지

#144 fix: 프로필이 적용이 안되는 버그, 에티터 수정시 입력 이전 Length가 표기 되지않는 버그 수정
  src/components/common/HeaderAfterLogin.tsx
  src/components/common/TextEditor/utils/hooks/useTextEditor.tsx
Labels: [🐞 BugFix ], 👽 창환, [ 🛠️ Suggestion]
