Repository Chiman2937/team1-w1k1ed-project, pull requests merged in 2025-07, with the labels that each got.

#3 feat: 버튼 공통 컴포넌트
  next.config.ts
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/images/logo.svg
  src/assets/images/type=image1.svg
  src/assets/images/type=image10.svg
  src/assets/images/type=image11.svg
  src/assets/images/type=image12.svg
  src/assets/images/type=image2.svg
  src/assets/images/type=image3.svg
  src/assets/images/type=image4.svg
  src/assets/images/type=image5.svg
  src/assets/images/type=image6.svg
  src/assets/images/type=image7.svg
  src/assets/images/type=image8.svg
  src/assets/images/type=image9.svg
  src/assets/images/type=menu.svg
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/common/Nav.tsx
  svg.d.ts
Labels: 🎨 Html&css

#4 feat: 클립보드에 복사 버튼 공통 컴포넌트
  src/app/globals.css
  src/assets/images/icon-link.svg
  src/components/common/CopyToClipboard.tsx
  src/utils/truncateText.ts
Labels: ✨ Feature

#5 feat: Input 컴포넌트
  package-lock.json
  package.json
  src/app/(auth)/login/page.tsx
  src/components/common/Input.tsx
Labels: ✨ Feature

#14 fix: font size 정의 수정(Tailwind.config.ts 파일 추가)
  src/app/globals.css
  tailwind.config.ts
Labels: [🎨 Html&css ], 😎<Chiman/>😎

#21 feat: board/[id] 페이지 댓글 수정 기능 추가
  src/app/boards/[id]/page.tsx
  src/components/page/boardDetail/BoardComment.tsx
  src/components/page/boardDetail/BoardContent.tsx
  src/components/page/boardDetail/CommentEdit.tsx
Labels: [✨ Feature ], [🎨 Html&css ]

#24 feat: 위키 상세페이지 초기진입 페이지 디자인 완료(글 내용 제외)
  package-lock.json
  src/app/testtoast/ToastSection.tsx
  src/app/wiki/[code]/page.tsx
  src/components/common/Snackbar.tsx
  src/components/page/wikicode/Editor/Editor.tsx
  src/components/page/wikicode/Viewer/ProfileViewer/ProfileViewer.tsx
  src/components/page/wikicode/Viewer/ProfileViewer/components/ProfileContentViewer.tsx
  src/components/page/wikicode/Viewer/ProfileViewer/components/ProfileField.tsx
  src/components/page/wikicode/Viewer/ProfileViewer/components/ProfileImageViewer.tsx
  src/components/page/wikicode/Viewer/TitleViewer/TitleViewer.tsx
  src/components/page/wikicode/Viewer/Viewer.tsx
  src/components/page/wikicode/WikiDetailSection.tsx
  tailwind.config.ts
Labels: [✨ Feature ], [🎨 Html&css ], 😎<Chiman/>😎

#37 chore: Input 컴포넌트 반응형 디자인 수정
  package-lock.json
  src/api/authAPI.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/mypage/page.tsx
  src/components/common/Input.tsx
  src/components/common/PasswordChangeForm.tsx
  src/components/common/WikiCreateForm.tsx
  src/lib/axios.ts
Labels: [✨ Feature ], [🎨 Html&css ], [🔨 Refactor ]

#38 feat: Text Editor 링크, 이미지, 로컬 동영상, 유튜브 동영상 삽입 기능 추가
  package-lock.json
  package.json
  src/app/globals.css
  src/app/testeditor/EditorButton.tsx
  src/app/testeditor/LocalVideo.ts
  src/app/testeditor/TextEditor.tsx
  src/app/testeditor/TextEditorStyle.ts
  src/app/testeditor/YoutubeVideo.ts
  src/app/testeditor/page.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 😎<Chiman/>😎

#36 feat: wikilist 페이지 기능구현
  src/app/wikilist/layout.tsx
  src/app/wikilist/page.tsx
  src/assets/images/search-no-result.png
  src/components/common/Pagination.tsx
  src/components/common/SearchBar.tsx
  src/components/page/wikilist/PaginationButton.tsx
  src/components/page/wikilist/SearchResultSummary.tsx
  src/components/page/wikilist/WikiListCard.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 💆🏻‍♂️진선

#41 refactor: TextEditor.tsx components 폴더로 이동, 구조 리팩토링
  src/app/globals.css
  src/app/testeditor/TextEditor.tsx
  src/app/testeditor/page.tsx
  src/components/common/TextEditor/TextEditor.tsx
  src/components/common/TextEditor/textarea/editorHtmlStyle.css
  src/components/common/TextEditor/toolbar/components/EditorButton.tsx
  src/components/common/TextEditor/toolbar/components/Separator.tsx
  src/components/common/TextEditor/toolbar/toolBarStyle.ts
  src/components/common/TextEditor/utils/extensions/LocalVideo.ts
  src/components/common/TextEditor/utils/extensions/YoutubeVideo.ts
  src/components/common/TextEditor/utils/handlers/handleImageSelect.ts
  src/components/common/TextEditor/utils/handlers/handleLinkSelect.ts
  src/components/common/TextEditor/utils/handlers/handleVideoSelect.ts
  src/components/common/TextEditor/utils/handlers/handleYoutubeSelect.ts
  src/components/common/TextEditor/utils/hooks/useTextEditor.tsx
  src/components/common/TextEditor/utils/hooks/useTextEditorForceUpdate.tsx
Labels: [🔨 Refactor ], 😎<Chiman/>😎

#48 feat: modal
  package-lock.json
  package.json
  src/app/testmodals/page.tsx
Labels: [✨ Feature ], 👽 창환

#55 feat: edit 페이지 구성
  src/app/boards/[id]/edit/page.tsx
  src/assets/images/default_profile.svg
  src/assets/images/type=delete.svg
  src/assets/images/type=edit.svg
  src/components/page/boardDetail/BoardComment.tsx
  src/components/page/boardDetail/BoardDetail.tsx
  src/components/page/boardDetail/BoardDetailButton.tsx
  src/components/page/boardDetail/BoardInfo.tsx
Labels: [✨ Feature ], [🔨 Refactor ], 👽 창환

#49 refactor: authAPI파일에 resetPassword 추가 + PasswordChangeForm에 zod+react-hook-form 적용
  src/api/authAPI.ts
  src/components/common/CTASection.tsx
  src/components/common/Footer.tsx
  src/components/common/HeaderAfterLogin.tsx
  src/components/common/HeaderBeforeLogin.tsx
  src/components/common/HeroSection.tsx
  src/components/common/PasswordChangeForm.tsx
  src/components/common/ShareSection.tsx
  src/components/common/ViewSection.tsx
Labels: [🔨 Refactor ], 🤓민지

#57 feat: ContextAPI 기반 인증 시스템 구현 및 토큰 관리
  README.md
  package-lock.json
  package.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/layout.tsx
  src/components/common/HeaderDropdown.tsx
  src/components/layout/AuthHeaderRenderer.tsx
  src/context/AuthContext.tsx
  src/lib/axios.ts
  src/types/user.d.ts
Labels: [✨ Feature ], [📬 API ], [🔨 Refactor ]

#59 fix: TextEditor 커스텀 이미지 익스텐션 추가, TextEditor Link OpenGraph 요청 CORS 에러 문제 해결
  src/components/common/TextEditor/ToolBar.tsx
  src/components/common/TextEditor/modals/LinkModal.tsx
  src/components/common/TextEditor/textarea/nodeEditStyle.css
  src/components/common/TextEditor/textarea/nodeImageStyle.css
  src/components/common/TextEditor/utils/extensions/CustomImageExtension.ts
  src/components/common/TextEditor/utils/handlers/handleImageSelect.ts
  src/components/common/TextEditor/utils/handlers/handleVideoSelect.ts
  src/components/common/TextEditor/utils/hooks/useTextEditor.tsx
Labels: [✨ Feature ], [🐞 BugFix ], [📬 API ], [🔨 Refactor ], 😎<Chiman/>😎

#63 feat: 이미지, 비디오 Cloudinary 업로드 API 작업
  src/api/clients/CloudinaryClient.ts
  src/api/uploadFileAPI.ts
  src/app/testupload/page.tsx
Labels: [✨ Feature ], [📬 API ], 😎<Chiman/>😎

#67 refactor: ssr to csr
  src/app/boards/[id]/page.tsx
  src/components/common/TextEditor/ToolBar.tsx
  src/components/page/boardDetail/BoardDetail.tsx
  src/components/page/boardDetail/BoardDetailButton.tsx
  src/components/page/boardDetail/BoardEdit.tsx
  src/components/page/boardDetail/BoardInfo.tsx
  src/lib/articleApi.ts
Labels: [🔨 Refactor ], 👽 창환

#66 fix: 중간점검 피드백 반영
  package-lock.json
  src/app/wikilist/page.tsx
  src/components/common/CopyToClipboard.tsx
  src/components/common/Pagination.tsx
  src/components/common/SearchBar.tsx
  src/components/page/wikilist/NoResultFallback.tsx
  src/components/page/wikilist/PaginationButton.tsx
  src/components/page/wikilist/SearchResultSummary.tsx
  src/components/page/wikilist/WikiListCard.tsx
Labels: [🎨 Html&css ], [🐞 BugFix ], 💆🏻‍♂️진선

#70 refactor: Text editor Toolbar.tsx 이미지, 동영상 모달 적용 건 원복
  src/components/common/TextEditor/ToolBar.tsx
  src/components/common/TextEditor/toolbar/components/LinkModal/LinkModal.tsx
  src/components/common/TextEditor/toolbar/components/LinkModal/components/LinkPreview.tsx
  src/components/common/TextEditor/utils/nodeWrapper/createWrapperElement.ts
Labels: [🔨 Refactor ]

#76 feat: addboard 페이지
  src/api/articleApi.ts
  src/app/addboard/page.tsx
  src/app/boards/[id]/page.tsx
  src/app/globals.css
  src/components/page/boardDetail/BoardComment.tsx
  src/components/page/boardDetail/BoardComments.tsx
  src/components/page/boardDetail/BoardContent.tsx
  src/components/page/boardDetail/BoardDetail.tsx
  src/components/page/boardDetail/BoardEdit.tsx
  src/components/page/boardDetail/BoardInfo.tsx
  src/components/page/boardDetail/BoardSkeleton.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 👽 창환

#78 fix: 토큰 만료 기간 연장
  src/app/(auth)/login/page.tsx
  src/context/AuthContext.tsx
Labels: [🐞 BugFix ], [📬 API ], [🔨 Refactor ], ☘️다인

#81 feat: profilesAPI 생성 후 적용
  package-lock.json
  package.json
  src/api/authAPI.ts
  src/api/profile/postProfilesAPI.ts
  src/app/mypage/page.tsx
  src/app/passwordChangePage/page.tsx
  src/app/settings/page.tsx
  src/components/common/AnswerInput.tsx
  src/components/common/Button.tsx
  src/components/common/CTASection.tsx
  src/components/common/Footer.tsx
  src/components/common/HeaderAfterLogin.tsx
  src/components/common/HeaderDropdown.tsx
  src/components/common/HeroSection.tsx
  src/components/common/NotificationItem.tsx
  src/components/common/NotificationPanel.tsx
  src/components/common/NotificationSwitch.tsx
  src/components/common/PasswordChangeForm.tsx
  src/components/common/QuestionSelection.tsx
  src/components/common/ShareSection.tsx
  src/components/common/Snackbar.tsx
  src/components/common/ViewSection.tsx
  src/components/common/WikiCreateForm.tsx
  src/store/notificationStore.ts
Labels: [📬 API ], 🤓민지

#82 fix: load spinner 색상 지정 기능 추가, 속도, 변화수치 지정 기능 추가
  src/app/testspinner/page.tsx
  src/components/common/LoadingSpinner/LoadingSpinner.tsx
  src/components/common/LoadingSpinner/dotBounce.module.css
  src/components/common/LoadingSpinner/dotCircle.module.css
  src/components/common/LoadingSpinner/lineCircle.module.css
Labels: [✨ Feature ], [🎨 Html&css ], 😎<Chiman/>😎

#90 feat: 위키 상세 페이지 디자인 작업 완료
  src/app/wiki/[code]/page.tsx
  src/components/common/TextEditor/textarea/nodeHtmlStyle.css
  src/components/common/TextEditor/viewer/viewerHtmlStyle.css
  src/components/page/wikicode/ProfileCard/ProfileCard.tsx
  src/components/page/wikicode/ProfileCard/components/ProfileField.tsx
  src/components/page/wikicode/ProfileCard/components/ProfileItemListEditor.tsx
  src/components/page/wikicode/ProfileContent.tsx/ProfileContent.tsx
  src/components/page/wikicode/ProfileIndex/ProfileIndex.tsx
  src/components/page/wikicode/ProfileTitle/ProfileTitle.tsx
  src/components/page/wikicode/ProfileTitle/components/QuestionModal.tsx
  src/components/page/wikicode/Timer/Timer.tsx
  src/components/page/wikicode/WikiDetailSection.tsx
  src/components/page/wikicode/WikiInfo/WikiInfo.tsx
  src/components/page/wikicode/components/ExpiredModal.tsx
  tailwind.config.ts
Labels: [✨ Feature ], [🎨 Html&css ], [🔨 Refactor ], 😎<Chiman/>😎

#98 feat: TextEditor 이미지 resize 기능 추가, 정렬 기능 추가
  src/components/common/TextEditor/ContentEditor.tsx
  src/components/common/TextEditor/textarea/ImageAlignToolBar.tsx
  src/components/common/TextEditor/utils/extensions/LocalImageExtension.ts
  src/components/common/TextEditor/utils/handlers/handleImageSelect.ts
Labels: [✨ Feature ], [🎨 Html&css ], 😎<Chiman/>😎

#100 fix: SnackBar 포지션 및 스타일 지정 로직 수정
  src/components/common/Snackbar.tsx
Labels: [🔨 Refactor ], 😎<Chiman/>😎

#92 feat: NotificationAPI setting with Zustand
  src/api/notificationsAPI.ts
  src/components/common/HeaderAfterLogin.tsx
  src/components/common/NotificationPanel.tsx
  src/components/common/NotificationSwitch.tsx
  src/store/notificationStore.ts
  src/store/useNotificationStore.ts
Labels: [✨ Feature ], [📬 API ], 🤓민지

#102 feat: 비밀번호 보기 & 이메일 기억하기 & Input 반응형 수정 + 이름 랜덤 숫자 생성
  package-lock.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/login/signIn.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/signup/signup.tsx
  src/components/common/Input.tsx
  src/utils/displayName.ts
Labels: [✨ Feature ], [🎨 Html&css ], [🔨 Refactor ], ☘️다인

#106 feat: 위키 상세페이지 프로필 이미지 선택 및 업로드(수정) 기능 추가
  next.config.ts
  src/components/page/wikicode/ProfileCard/ProfileCard.tsx
  src/components/page/wikicode/ProfileCard/components/ProfileImageEditor.tsx
  src/components/page/wikicode/ProfileCard/components/ProfileImageViewer.tsx
  src/components/page/wikicode/ProfileIndex/ProfileIndex.tsx
  src/components/page/wikicode/WikiDetailSection.tsx
  src/context/WikiContext.tsx
Labels: [✨ Feature ], [🎨 Html&css ], [🔨 Refactor ], 😎<Chiman/>😎

#112 fix: 위키상세페이지 작성 완료 제출 시 페이지 새로고침되도록 수정
  src/components/page/wikicode/WikiDetailSection.tsx
  src/hooks/useUnloadAlert.tsx
Labels: [✨ Feature ], [🔨 Refactor ], 😎<Chiman/>😎

#114 feat: 위키상세페이지 프로필 이미지 변경 시 기본 이미지 선택 기능 추가
  public/images/default_profile.svg
  src/api/profile/getProfileAPI.ts
  src/api/profile/patchProfileAPI.ts
  src/components/page/wikicode/ProfileCard/ProfileCard.tsx
  src/components/page/wikicode/ProfileCard/components/ProfileImageEditor.tsx
  src/components/page/wikicode/ProfileCard/components/ProfileImageViewer.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 😎<Chiman/>😎

#119 feat: 위키상세페이지 목차 클릭 시 해당 content 위치로 이동하는 기능 제작
  package-lock.json
  package.json
  src/components/common/TextEditor/utils/handlers/addIdToHeadings.ts
  src/components/common/TextEditor/utils/handlers/getHtmlFirstImageSrc.ts
  src/components/common/TextEditor/utils/handlers/getHtmlHeadings.ts
  src/components/common/TextEditor/utils/handlers/handleHtmlParse.ts
  src/components/common/TextEditor/utils/handlers/removeHeadingIds.ts
  src/components/common/TextEditor/utils/handlers/replaceAspectRatioToHeight.ts
  src/components/common/TextEditor/utils/hooks/useTextEditor.tsx
  src/components/common/TextEditor/viewer/viewerHtmlStyle.css
  src/components/page/wikicode/ProfileIndex/ProfileIndex.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 😎<Chiman/>😎

#125 feat: 회원가입 버튼 비활성화 && 이메일 중복 시 Input 에러클래스 적용
  src/app/(auth)/signup/signup.tsx
  src/components/common/Input.tsx
Labels: [✨ Feature ], [🔨 Refactor ], ☘️다인

#128 fix: ToastRender 삭제, 앱 로딩 중 삭제
  src/app/(auth)/login/page.tsx
  src/app/(auth)/login/signIn.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/signup/signup.tsx
  src/app/layout.tsx
Labels: ☘️다인
